services:
  sonarr:
    image: linuxserver/sonarr:latest
    volumes:
      - ./sonarr/config:/config
      - ./data:/data

  sonarr-remediator:
    image: ghcr.io/calmcacil/sonarr-remediator:latest
    volumes:
      - ./data:/data:ro
      - ./remediator-config:/config
    environment:
      - SRA_SONARR__URL=http://sonarr:8989
      - SRA_SONARR__API_KEY=${SONARR_API_KEY}
      - SRA_DRY_RUN=true
    depends_on:
      - sonarr
    stop_grace_period: 30s
